//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCategorizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeCategorizer.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector of client is expected to be one of the following: {0}. But actual value is {1}. Line with error: {2}.
        /// </summary>
        public static string ClientSectorNotInExpectedValues {
            get {
                return ResourceManager.GetString("ClientSectorNotInExpectedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next payment date of trade is expected to be a date but actual value is {0}. Line with error: {1}.
        /// </summary>
        public static string InvalidDateOfNextPayment {
            get {
                return ResourceManager.GetString("InvalidDateOfNextPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of columns, should be {0}. Line with error: {1}.
        /// </summary>
        public static string InvalidNumberOfColumnsInTradeLine {
            get {
                return ResourceManager.GetString("InvalidNumberOfColumnsInTradeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference date in file is not a valid date (line 1)..
        /// </summary>
        public static string InvalidReferenceDateInFileHeader {
            get {
                return ResourceManager.GetString("InvalidReferenceDateInFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trades in portfolio is not a valid number (line 2)..
        /// </summary>
        public static string InvalidValueForNumberOfTradesInFileHeader {
            get {
                return ResourceManager.GetString("InvalidValueForNumberOfTradesInFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of trade expected to be a number but actual value is {0}. Line with error: {1}.
        /// </summary>
        public static string TradeValueIsNotANumber {
            get {
                return ResourceManager.GetString("TradeValueIsNotANumber", resourceCulture);
            }
        }
    }
}
